root: true
extends:
  - prettier
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
plugins:
  - import
  - prettier
  - '@typescript-eslint'
parser: '@typescript-eslint/parser'
rules:
  no-console: 1
  prettier/prettier: error
  arrow-body-style: 'off'
  prefer-arrow-callback: 'off'
  quotes: [ 'error', 'single' ]
settings:
  import/resolver:
    typescript: true
    node: true
parserOptions:
  ecmaVersion: 2022
ignorePatterns:
  - dist/
  - node_modules/
